# -*- coding: utf-8 -*-
"""mega_project_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRoUIwKPaaRoj8xc_n5u6l2s1rE-DGV-
"""

!pip install -q kaggle

import os

!kaggle datasets download -d aryashah2k/indian-medicinal-leaves-dataset

import zipfile

with zipfile.ZipFile('indian-medicinal-leaves-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('dataset')

import os, shutil

source_dir = 'dataset/Indian Medicinal Leaves Image Datasets/Medicinal Leaf dataset'
target_dir = 'dataset/selected'

selected_classes = ['Amla', 'Guava', 'Neem', 'Tulsi', 'Hibiscus']

# Clean old folder if exists (IMPORTANT)
if os.path.exists(target_dir):
    shutil.rmtree(target_dir)

os.makedirs(target_dir)

for cls in selected_classes:
    shutil.copytree(os.path.join(source_dir, cls),
                    os.path.join(target_dir, cls))

print("Classes:", os.listdir(target_dir))

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data = train_datagen.flow_from_directory(
    'dataset/selected',
    target_size=(160,160),
    batch_size=16,
    class_mode='categorical',
    subset='training'
)

val_data = val_datagen.flow_from_directory(
    'dataset/selected',
    target_size=(160,160),
    batch_size=16,
    class_mode='categorical',
    subset='validation'
)

print("Class mapping:", train_data.class_indices)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(160,160,3)
)

# Freeze all layers
for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.4)(x)

# IMPORTANT FIX (auto match classes)
output = Dense(len(train_data.class_indices), activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(patience=3, restore_best_weights=True)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=15,
    callbacks=[early_stop]
)

# Unfreeze only last 15 layers (NOT MORE)
for layer in base_model.layers[-15:]:
    layer.trainable = True

model.compile(
    optimizer=Adam(learning_rate=0.00005),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

model.summary()

loss, accuracy = model.evaluate(val_data)
print(f"\n🔥 Final Accuracy: {accuracy*100:.2f}%")

from google.colab import files
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

uploaded = files.upload()

class_labels = list(train_data.class_indices.keys())

for img_name in uploaded.keys():
    img = image.load_img(img_name, target_size=(160,160))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    predicted_class = class_labels[np.argmax(prediction)]
    confidence = np.max(prediction)

    plt.imshow(img)
    plt.title(f"{predicted_class} ({confidence*100:.2f}%)")
    plt.axis('off')
    plt.show()

model.save('leaf_model.h5')

from google.colab import files
files.download('leaf_model.h5')

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Predictions
y_pred = model.predict(val_data)
y_pred_classes = np.argmax(y_pred, axis=1)

# True labels
y_true = val_data.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_classes)

# Class labels
class_labels = list(val_data.class_indices.keys())

# Plot
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_labels,
            yticklabels=class_labels)

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

loss, accuracy = model.evaluate(val_data)
print(f"Final Accuracy: {accuracy*100:.2f}%")
print(f"Final Loss: {loss:.4f}")

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])

plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'])

plt.show()

model.summary()
print("Total Parameters:", model.count_params())

print("Train samples:", train_data.samples)
print("Validation samples:", val_data.samples)
print("Classes:", train_data.class_indices)

val_data = val_datagen.flow_from_directory(
    'dataset/selected',
    target_size=(160,160),
    batch_size=16,
    class_mode='categorical',
    subset='validation',
    shuffle=False   # 🔥 IMPORTANT
)

y_pred = model.predict(val_data)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = val_data.classes

from sklearn.metrics import classification_report
class_labels = list(val_data.class_indices.keys())

print(classification_report(y_true, y_pred_classes, target_names=class_labels))